// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.4
// source: consts.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 该结构与consts结构一样，客户端服务器共用，只要定义就不能改变
type AccountType int32

const (
	AccountType_DEVICEID AccountType = 0
	AccountType_WX       AccountType = 1
	AccountType_FB       AccountType = 2
	AccountType_GIT      AccountType = 3
)

// Enum value maps for AccountType.
var (
	AccountType_name = map[int32]string{
		0: "DEVICEID",
		1: "WX",
		2: "FB",
		3: "GIT",
	}
	AccountType_value = map[string]int32{
		"DEVICEID": 0,
		"WX":       1,
		"FB":       2,
		"GIT":      3,
	}
)

func (x AccountType) Enum() *AccountType {
	p := new(AccountType)
	*p = x
	return p
}

func (x AccountType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccountType) Descriptor() protoreflect.EnumDescriptor {
	return file_consts_proto_enumTypes[0].Descriptor()
}

func (AccountType) Type() protoreflect.EnumType {
	return &file_consts_proto_enumTypes[0]
}

func (x AccountType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccountType.Descriptor instead.
func (AccountType) EnumDescriptor() ([]byte, []int) {
	return file_consts_proto_rawDescGZIP(), []int{0}
}

type GameState int32

const (
	GameState_IDLE       GameState = 0
	GameState_WAIT       GameState = 1
	GameState_WAITREADY  GameState = 2
	GameState_CANCEL     GameState = 3
	GameState_COUNTDOWN  GameState = 4
	GameState_GAMING     GameState = 5
	GameState_SETTLEMENT GameState = 6
)

// Enum value maps for GameState.
var (
	GameState_name = map[int32]string{
		0: "IDLE",
		1: "WAIT",
		2: "WAITREADY",
		3: "CANCEL",
		4: "COUNTDOWN",
		5: "GAMING",
		6: "SETTLEMENT",
	}
	GameState_value = map[string]int32{
		"IDLE":       0,
		"WAIT":       1,
		"WAITREADY":  2,
		"CANCEL":     3,
		"COUNTDOWN":  4,
		"GAMING":     5,
		"SETTLEMENT": 6,
	}
)

func (x GameState) Enum() *GameState {
	p := new(GameState)
	*p = x
	return p
}

func (x GameState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GameState) Descriptor() protoreflect.EnumDescriptor {
	return file_consts_proto_enumTypes[1].Descriptor()
}

func (GameState) Type() protoreflect.EnumType {
	return &file_consts_proto_enumTypes[1]
}

func (x GameState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GameState.Descriptor instead.
func (GameState) EnumDescriptor() ([]byte, []int) {
	return file_consts_proto_rawDescGZIP(), []int{1}
}

type GameSubState int32

const (
	GameSubState_SUBSTATE_NONE       GameSubState = 0
	GameSubState_WAITREADY_PROFILE   GameSubState = 1
	GameSubState_WAITREADY_COUNTDOWN GameSubState = 2
	GameSubState_WAITREADY_READYLIST GameSubState = 3
	GameSubState_COUNTDOWN_BEGIN     GameSubState = 4
	GameSubState_GAME_BEGIN          GameSubState = 5
	GameSubState_GAME_LOSE           GameSubState = 6
	GameSubState_SETTLEMENT_BEGIN    GameSubState = 7
	GameSubState_SETTLEMENT_END      GameSubState = 8
)

// Enum value maps for GameSubState.
var (
	GameSubState_name = map[int32]string{
		0: "SUBSTATE_NONE",
		1: "WAITREADY_PROFILE",
		2: "WAITREADY_COUNTDOWN",
		3: "WAITREADY_READYLIST",
		4: "COUNTDOWN_BEGIN",
		5: "GAME_BEGIN",
		6: "GAME_LOSE",
		7: "SETTLEMENT_BEGIN",
		8: "SETTLEMENT_END",
	}
	GameSubState_value = map[string]int32{
		"SUBSTATE_NONE":       0,
		"WAITREADY_PROFILE":   1,
		"WAITREADY_COUNTDOWN": 2,
		"WAITREADY_READYLIST": 3,
		"COUNTDOWN_BEGIN":     4,
		"GAME_BEGIN":          5,
		"GAME_LOSE":           6,
		"SETTLEMENT_BEGIN":    7,
		"SETTLEMENT_END":      8,
	}
)

func (x GameSubState) Enum() *GameSubState {
	p := new(GameSubState)
	*p = x
	return p
}

func (x GameSubState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GameSubState) Descriptor() protoreflect.EnumDescriptor {
	return file_consts_proto_enumTypes[2].Descriptor()
}

func (GameSubState) Type() protoreflect.EnumType {
	return &file_consts_proto_enumTypes[2]
}

func (x GameSubState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GameSubState.Descriptor instead.
func (GameSubState) EnumDescriptor() ([]byte, []int) {
	return file_consts_proto_rawDescGZIP(), []int{2}
}

type RoomType int32

const (
	RoomType_ROOMTYPE_NONE RoomType = 0
	RoomType_QUICK         RoomType = 1
	RoomType_MATCH         RoomType = 2
)

// Enum value maps for RoomType.
var (
	RoomType_name = map[int32]string{
		0: "ROOMTYPE_NONE",
		1: "QUICK",
		2: "MATCH",
	}
	RoomType_value = map[string]int32{
		"ROOMTYPE_NONE": 0,
		"QUICK":         1,
		"MATCH":         2,
	}
)

func (x RoomType) Enum() *RoomType {
	p := new(RoomType)
	*p = x
	return p
}

func (x RoomType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoomType) Descriptor() protoreflect.EnumDescriptor {
	return file_consts_proto_enumTypes[3].Descriptor()
}

func (RoomType) Type() protoreflect.EnumType {
	return &file_consts_proto_enumTypes[3]
}

func (x RoomType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoomType.Descriptor instead.
func (RoomType) EnumDescriptor() ([]byte, []int) {
	return file_consts_proto_rawDescGZIP(), []int{3}
}

type TableType int32

const (
	TableType_TABLETYPE_NONE TableType = 0
	TableType_NORMAL         TableType = 1
	TableType_HAPPY          TableType = 2
)

// Enum value maps for TableType.
var (
	TableType_name = map[int32]string{
		0: "TABLETYPE_NONE",
		1: "NORMAL",
		2: "HAPPY",
	}
	TableType_value = map[string]int32{
		"TABLETYPE_NONE": 0,
		"NORMAL":         1,
		"HAPPY":          2,
	}
)

func (x TableType) Enum() *TableType {
	p := new(TableType)
	*p = x
	return p
}

func (x TableType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TableType) Descriptor() protoreflect.EnumDescriptor {
	return file_consts_proto_enumTypes[4].Descriptor()
}

func (TableType) Type() protoreflect.EnumType {
	return &file_consts_proto_enumTypes[4]
}

func (x TableType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TableType.Descriptor instead.
func (TableType) EnumDescriptor() ([]byte, []int) {
	return file_consts_proto_rawDescGZIP(), []int{4}
}

var File_consts_proto protoreflect.FileDescriptor

var file_consts_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2a, 0x34, 0x0a, 0x0b, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x0c, 0x0a, 0x08, 0x44, 0x45, 0x56, 0x49, 0x43, 0x45, 0x49, 0x44,
	0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x57, 0x58, 0x10, 0x01, 0x12, 0x06, 0x0a, 0x02, 0x46, 0x42,
	0x10, 0x02, 0x12, 0x07, 0x0a, 0x03, 0x47, 0x49, 0x54, 0x10, 0x03, 0x2a, 0x65, 0x0a, 0x09, 0x47,
	0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x49, 0x44, 0x4c, 0x45,
	0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x57, 0x41, 0x49, 0x54, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09,
	0x57, 0x41, 0x49, 0x54, 0x52, 0x45, 0x41, 0x44, 0x59, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x43,
	0x41, 0x4e, 0x43, 0x45, 0x4c, 0x10, 0x03, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x4f, 0x55, 0x4e, 0x54,
	0x44, 0x4f, 0x57, 0x4e, 0x10, 0x04, 0x12, 0x0a, 0x0a, 0x06, 0x47, 0x41, 0x4d, 0x49, 0x4e, 0x47,
	0x10, 0x05, 0x12, 0x0e, 0x0a, 0x0a, 0x53, 0x45, 0x54, 0x54, 0x4c, 0x45, 0x4d, 0x45, 0x4e, 0x54,
	0x10, 0x06, 0x2a, 0xc8, 0x01, 0x0a, 0x0c, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x75, 0x62, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x12, 0x11, 0x0a, 0x0d, 0x53, 0x55, 0x42, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f,
	0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x15, 0x0a, 0x11, 0x57, 0x41, 0x49, 0x54, 0x52, 0x45,
	0x41, 0x44, 0x59, 0x5f, 0x50, 0x52, 0x4f, 0x46, 0x49, 0x4c, 0x45, 0x10, 0x01, 0x12, 0x17, 0x0a,
	0x13, 0x57, 0x41, 0x49, 0x54, 0x52, 0x45, 0x41, 0x44, 0x59, 0x5f, 0x43, 0x4f, 0x55, 0x4e, 0x54,
	0x44, 0x4f, 0x57, 0x4e, 0x10, 0x02, 0x12, 0x17, 0x0a, 0x13, 0x57, 0x41, 0x49, 0x54, 0x52, 0x45,
	0x41, 0x44, 0x59, 0x5f, 0x52, 0x45, 0x41, 0x44, 0x59, 0x4c, 0x49, 0x53, 0x54, 0x10, 0x03, 0x12,
	0x13, 0x0a, 0x0f, 0x43, 0x4f, 0x55, 0x4e, 0x54, 0x44, 0x4f, 0x57, 0x4e, 0x5f, 0x42, 0x45, 0x47,
	0x49, 0x4e, 0x10, 0x04, 0x12, 0x0e, 0x0a, 0x0a, 0x47, 0x41, 0x4d, 0x45, 0x5f, 0x42, 0x45, 0x47,
	0x49, 0x4e, 0x10, 0x05, 0x12, 0x0d, 0x0a, 0x09, 0x47, 0x41, 0x4d, 0x45, 0x5f, 0x4c, 0x4f, 0x53,
	0x45, 0x10, 0x06, 0x12, 0x14, 0x0a, 0x10, 0x53, 0x45, 0x54, 0x54, 0x4c, 0x45, 0x4d, 0x45, 0x4e,
	0x54, 0x5f, 0x42, 0x45, 0x47, 0x49, 0x4e, 0x10, 0x07, 0x12, 0x12, 0x0a, 0x0e, 0x53, 0x45, 0x54,
	0x54, 0x4c, 0x45, 0x4d, 0x45, 0x4e, 0x54, 0x5f, 0x45, 0x4e, 0x44, 0x10, 0x08, 0x2a, 0x33, 0x0a,
	0x08, 0x52, 0x6f, 0x6f, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x12, 0x11, 0x0a, 0x0d, 0x52, 0x4f, 0x4f,
	0x4d, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05,
	0x51, 0x55, 0x49, 0x43, 0x4b, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x4d, 0x41, 0x54, 0x43, 0x48,
	0x10, 0x02, 0x2a, 0x36, 0x0a, 0x09, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x12, 0x0a, 0x0e, 0x54, 0x41, 0x42, 0x4c, 0x45, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x4e, 0x4f, 0x4e,
	0x45, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x4e, 0x4f, 0x52, 0x4d, 0x41, 0x4c, 0x10, 0x01, 0x12,
	0x09, 0x0a, 0x05, 0x48, 0x41, 0x50, 0x50, 0x59, 0x10, 0x02, 0x42, 0x08, 0x5a, 0x06, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_consts_proto_rawDescOnce sync.Once
	file_consts_proto_rawDescData = file_consts_proto_rawDesc
)

func file_consts_proto_rawDescGZIP() []byte {
	file_consts_proto_rawDescOnce.Do(func() {
		file_consts_proto_rawDescData = protoimpl.X.CompressGZIP(file_consts_proto_rawDescData)
	})
	return file_consts_proto_rawDescData
}

var file_consts_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_consts_proto_goTypes = []interface{}{
	(AccountType)(0),  // 0: proto.AccountType
	(GameState)(0),    // 1: proto.GameState
	(GameSubState)(0), // 2: proto.GameSubState
	(RoomType)(0),     // 3: proto.RoomType
	(TableType)(0),    // 4: proto.TableType
}
var file_consts_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_consts_proto_init() }
func file_consts_proto_init() {
	if File_consts_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_consts_proto_rawDesc,
			NumEnums:      5,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_consts_proto_goTypes,
		DependencyIndexes: file_consts_proto_depIdxs,
		EnumInfos:         file_consts_proto_enumTypes,
	}.Build()
	File_consts_proto = out.File
	file_consts_proto_rawDesc = nil
	file_consts_proto_goTypes = nil
	file_consts_proto_depIdxs = nil
}
